

ebootstrap-configure-make-conf() {
    local MAKE_CONF=${EROOT}/etc/portage/make.conf
    local config=()
    local vars=()
    local line
    local append=()

    if [[ -f ${MAKE_CONF} ]]; then
        while read line; do
            case "${line}" in
                *=*)
                    vars+=( "${line%=*}" )
                    #config[${line%=*}]="${line#*=}"
                    ;;
            esac
        done < "${MAKE_CONF}"
    else
        #touch "${MAKE_CONF}"
        printf "# Generated by ebootstrap\n" > ${MAKE_CONF}
    fi

    {
        #echo MAKE_CONF=${MAKE_CONF} >&2
        while read line; do
            #echo "line: $line" >&2
            case "${line}" in
                *=*)
                    if has "${line%=*}" "${vars[@]}"; then
                        #sed -i -e "s/^${line%=*}=.*$/${line%=*}=\"${line#*=}\"/" ${MAKE_CONF}
                        printf "s/^${line%=*}=.*$/${line%=*}=\"${line#*=}\"/\n"
                    else
                        #echo "${line%=*}=\"${line#*=}\""
                        #printf "$ {\na ${line%=*}=\"${line#*=}\"\n}\n"
                        append+=( "${line%=*}=\"${line#*=}\"" )
                    fi
                    ;;
                *)
                    #echo "${line}"
                    #printf "$ {\na ${line}\n}\n"
                    append+=( "${line}" )
                    ;;
            esac
        done <<< "${E_MAKE_CONF}"
        if [[ ${#append[@]} > 0 ]]; then
            #printf "$ {\n"
            printf "  a %s\n" "${append[@]}"
            #printf "}\n"
        fi
        
    #} >> ${MAKE_CONF}
    #} |tee /dev/stderr | sed -i -f - ${MAKE_CONF}
    } | sed -i -f - ${MAKE_CONF}

}
