

ebootstrap-configure-make-conf() {
    local MAKE_CONF=${EROOT}/etc/portage/make.conf
    local config=()
    local vars=()
    local line
    local append=()

    if [[ ! -v MAKE_CONF_DEFAULT ]]; then
        local MAKE_CONF_DEFAULT="
                  PORTDIR=\"/var/db/repos/gentoo\"
                  PKGDIR=\"/var/cache/binpkg\"
                  DISTDIR=\"/var/cache/distfiles\""
    fi

    if [[ ! -f ${MAKE_CONF} ]]; then
        printf "# Generated by ebootstrap\n" > ${MAKE_CONF}
        preprocess-make-conf-vars "${MAKE_CONF_DEFAULT}" >> ${MAKE_CONF}
    fi

    # read the existing variable names in the file
    while read line; do
        case "${line}" in
            *=*)
                vars+=( "${line%=*}" )
                ;;
        esac
    done < "${MAKE_CONF}"

    # generate and process sed edits to the default config
    {
        while read line; do
            case "${line}" in
                *=*)
                    if has "${line%=*}" "${vars[@]}"; then
                        printf "s/^${line%=*}=.*$/${line%=*}=\"${line#*=}\"/\n"
                    else
                        append+=( "${line%=*}=\"${line#*=}\"" )
                    fi
                    ;;
                *)
                    append+=( "${line}" )
                    ;;
            esac
        done <<< "${E_MAKE_CONF}"
        if [[ ${#append[@]} > 0 ]]; then
            printf "$ {\n"
            printf "  a %s\n" "${append[@]}"
            printf "}\n"
        fi
        
    #} >> ${MAKE_CONF}
    #} |tee /dev/stderr | sed -i -f - ${MAKE_CONF}
    } | sed -i -f - ${MAKE_CONF}

}
